import React,{createContext,useCallback,useContext,useEffect,useMemo,useState} from 'react';
import type {ApprovalRequest,Challenge} from '../types';import {useAuth} from './AuthContext';
export interface NewChallengeInput{title:string;description:string;domain:string;country:string;state:string;district:string;city:string;pincode:string;latitude?:number;longitude?:number;locationAccuracy?:number;mediaUrl?:string;mediaType?:'image'|'video';}
interface ChallengeValue{all:Challenge[]; duplicateCheck:(input:{title:string;description:string;state:string;district:string})=>Promise<{duplicateChallenge?:Challenge|null;similarity?:number}>;mine:Challenge[];ready:boolean;getById:(id:string)=>Challenge|undefined;addChallenge:(input:NewChallengeInput)=>Promise<Challenge>;claimForTeam:(id:string,teamName:string,solution:{title:string;description:string})=>Promise<Challenge>;submitSolution:(id:string,title:string,description:string)=>Promise<Challenge>;postProgress:(id:string,note:string)=>Promise<Challenge>;expressIndustryInterest:(id:string)=>Promise<Challenge>;sendProposal:(id:string,data:{idea:string;offer?:string;bid?:string})=>Promise<Challenge>;respondProposal:(id:string,proposalId:string,decision:'accept'|'reject',note?:string)=>Promise<Challenge>;submitCompletion:(id:string,summary:string,proofs:string[],beforeMedia?:{url:string;type:'image'|'video'},afterMedia?:{url:string;type:'image'|'video'})=>Promise<Challenge>; aiSuggestion:(input:{title:string;description:string;domain:string})=>Promise<any>; universityLeaderboard:()=>Promise<any[]>;supportChallenge:(id:string)=>Promise<Challenge>;requestVerification:(id:string)=>Promise<ApprovalRequest>;approve:(id:string)=>Promise<Challenge>;reject:(id:string)=>Promise<Challenge>;approvalRequests:ApprovalRequest[];pendingApprovalCount:number;approveRequest:(id:string)=>Promise<ApprovalRequest>;rejectRequest:(id:string)=>Promise<ApprovalRequest>;deleteChallenge:(id:string)=>Promise<void>;deleteApprovalRequest:(id:string)=>Promise<void>;adminUsers:()=>Promise<any[]>;deleteUser:(id:string)=>Promise<void>;}
const C=createContext<ChallengeValue|null>(null);const headers=()=>{const token=localStorage.getItem('samadhan-token')||'';return {'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})};};
async function request(url:string,options:RequestInit={}){const r=await fetch(url,options);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d;}
export function ChallengeProvider({children}:{children:React.ReactNode}){const{user}=useAuth();const[all,setAll]=useState<Challenge[]>([]);const[approvalRequests,setApprovalRequests]=useState<ApprovalRequest[]>([]);const[ready,setReady]=useState(false);
 const refresh=useCallback(async()=>{try{const cs=await request('/api/challenges',{headers:headers()});setAll(cs);if(user?.role==='admin')setApprovalRequests(await request('/api/approval-requests',{headers:headers()}));}finally{setReady(true)}},[user]);
 useEffect(()=>{void refresh();const es=new EventSource('/api/events');es.onmessage=()=>void refresh();return()=>es.close()},[refresh]);
 const updateLocal=(c:Challenge)=>{setAll(p=>p.map(x=>x.id===c.id?c:x));return c};
 const duplicateCheck=useCallback(async(input:{title:string;description:string;state:string;district:string})=>request('/api/challenges/check-duplicate',{method:'POST',headers:headers(),body:JSON.stringify(input)}),[]);
 const addChallenge=useCallback(async(input:NewChallengeInput)=>{const c=await request('/api/challenges',{method:'POST',headers:headers(),body:JSON.stringify(input)});setAll(p=>[c,...p.filter(x=>x.id!==c.id)]);return c},[]);
 const claimForTeam=useCallback(async(id:string,teamName:string,solution:{title:string;description:string})=>{const d=await request(`/api/challenges/${id}/claim`,{method:'POST',headers:headers(),body:JSON.stringify({teamName,...(solution||{})})});return updateLocal(d.challenge)},[]);
 const submitSolution=useCallback(async(id:string,title:string,description:string)=>{const d=await request(`/api/challenges/${id}/solution`,{method:'POST',headers:headers(),body:JSON.stringify({title,description})});return updateLocal(d.challenge)},[]);
 const postProgress=useCallback(async(id:string,note:string)=>{const c=await request(`/api/challenges/${id}/progress`,{method:'POST',headers:headers(),body:JSON.stringify({note})});return updateLocal(c)},[]);
 const expressIndustryInterest=useCallback(async(id:string)=>{const d=await request(`/api/challenges/${id}/industry-interest`,{method:'POST',headers:headers()});return updateLocal(d.challenge)},[]);
 const sendProposal=useCallback(async(id:string,data:{idea:string;offer?:string;bid?:string})=>{const c=await request(`/api/challenges/${id}/proposals`,{method:'POST',headers:headers(),body:JSON.stringify(data)});return updateLocal(c)},[]);
 const respondProposal=useCallback(async(id:string,proposalId:string,decision:'accept'|'reject',note?:string)=>{const c=await request(`/api/challenges/${id}/proposals/${proposalId}/respond`,{method:'POST',headers:headers(),body:JSON.stringify({decision,note})});return updateLocal(c)},[]);
 const submitCompletion=useCallback(async(id:string,summary:string,proofs:string[],beforeMedia?:{url:string;type:'image'|'video'},afterMedia?:{url:string;type:'image'|'video'})=>{const d=await request(`/api/challenges/${id}/completion`,{method:'POST',headers:headers(),body:JSON.stringify({summary,proofs,beforeMedia,afterMedia})});return updateLocal(d.challenge)},[]);
 const aiSuggestion=useCallback(async(input:{title:string;description:string;domain:string})=>request('/api/ai/solution-suggestion',{method:'POST',headers:headers(),body:JSON.stringify(input)}),[]);
 const universityLeaderboard=useCallback(async()=>request('/api/leaderboard/universities'),[]);
 const supportChallenge=useCallback(async(id:string)=>updateLocal(await request(`/api/challenges/${id}/support`,{method:'POST',headers:headers()})),[]);
 const requestVerification=useCallback(async(id:string)=>{const d=await request(`/api/challenges/${id}/verify-request`,{method:'POST',headers:headers()});updateLocal(d.challenge);return d.request},[]);
 const approveRequest=useCallback(async(id:string)=>{const d=await request(`/api/admin/approval-requests/${id}/approve`,{method:'POST',headers:headers()});setApprovalRequests(p=>p.map(x=>x.id===id?d.request:x));if(d.challenge)updateLocal(d.challenge);return d.request},[]);
 const rejectRequest=useCallback(async(id:string)=>{const d=await request(`/api/admin/approval-requests/${id}/reject`,{method:'POST',headers:headers()});setApprovalRequests(p=>p.map(x=>x.id===id?d.request:x));if(d.challenge)updateLocal(d.challenge);return d.request},[]);
 const deleteChallenge=useCallback(async(id:string)=>{await request(`/api/admin/challenges/${id}`,{method:'DELETE',headers:headers()});setAll(p=>p.filter(x=>x.id!==id));setApprovalRequests(p=>p.filter(x=>x.challengeId!==id));},[]);
 const deleteApprovalRequest=useCallback(async(id:string)=>{await request(`/api/admin/approval-requests/${id}`,{method:'DELETE',headers:headers()});setApprovalRequests(p=>p.filter(x=>x.id!==id));},[]);
 const adminUsers=useCallback(async()=>request('/api/admin/users',{headers:headers()}),[]);
 const deleteUser=useCallback(async(id:string)=>{await request(`/api/admin/users/${id}`,{method:'DELETE',headers:headers()});},[]);
 const approve=useCallback(async(id:string)=>updateLocal(await request(`/api/admin/challenges/${id}/approve`,{method:'POST',headers:headers()})),[]);const reject=useCallback(async(id:string)=>updateLocal(await request(`/api/admin/challenges/${id}/reject`,{method:'POST',headers:headers(),body:JSON.stringify({})})),[]);
 const mine=useMemo(()=>user?all.filter(c=>c.submittedByEmail===user.email||c.teamApplication?.contactEmail===user.email):[],[all,user]);
 const pendingApprovalCount=user?.role==='admin'?approvalRequests.filter(r=>r.status==='pending').length:0;
 return <C.Provider value={{all,mine,ready,getById:(id)=>all.find(c=>c.id===id),duplicateCheck,addChallenge,claimForTeam,submitSolution,postProgress,expressIndustryInterest,sendProposal,respondProposal,submitCompletion,aiSuggestion,universityLeaderboard,supportChallenge,requestVerification,approve,reject,approvalRequests,pendingApprovalCount,approveRequest,rejectRequest,deleteChallenge,deleteApprovalRequest,adminUsers,deleteUser}}>{children}</C.Provider>;
}
export function useChallenges(){const c=useContext(C);if(!c)throw new Error('useChallenges must be used inside ChallengeProvider');return c;}
